### ISSUE TITLE
生成的时间戳不规范

### ISSUE THREAD

**Issue by pengkobe** [xiadd/shorthand#8]
https://github.com/xiadd/shorthand/blob/bd8d53a71fb8b60394fa938d4f6a95a8f4c555e3/app/libs/getJsApiData.js#L36  

生成的时间戳超过了微信官方要求的 `10` 位十进制数字的限制

**Comment by xiadd** [comment]
这个仓库至今也快3年了，参考意义不是很大

**Comment by pengkobe** [comment]
👌
